'use strict';

var TEAM = {
  TASKCLUSTER: 'TaskCluster',
  REL_OPS: 'Release Operations',
  ENG_PROD: 'Engineering Productivity',
  BUILD: 'Build Systems Team',
  TESTS: 'Tests Platform',
  REL_ENG: 'Release Engineering'
};

var LABELS = {
  [TEAM.TASKCLUSTER]: 'default',
  [TEAM.REL_OPS]: 'primary',
  [TEAM.ENG_PROD]: 'success',
  [TEAM.BUILD]: 'info',
  [TEAM.TESTS]: 'warning',
  [TEAM.REL_ENG]: 'danger'
};

var TASK = {
  WORKER: 'TaskCluster worker ready',
  AMI: 'image/AMI ready',
  MACH: 'mach build set up',
  MOZHARNESS: 'mozharness config',
  TRY: 'try',
  BUILD_PEER: 'build peer review',
  SYMBOL: 'symbol upload',
  IMAGE: 'image creation',
  UNIT: 'unit',
  MOCHITEST: 'mochitest',
  REF: 'reftest',
  WEB_PLATFORM: 'web-platform-tests',
  E10S: 'e10s',
  TALOS: 'talos',
  TIER2: 'tier2',
  TIER1: 'tier1',
  SIGNED: 'signed builds',
  MAR: 'complete MAR',
  L10N: 'l10n'
};

var OWNERS = {
  [TASK.WORKER]: [TEAM.TASKCLUSTER],
  [TASK.AMI]: [TEAM.TASKCLUSTER, TEAM.REL_OPS],
  [TASK.MACH]: [],
  [TASK.MOZHARNESS]: [TEAM.REL_OPS, TEAM.TASKCLUSTER, TEAM.ENG_PROD],
  [TASK.TRY]: [TEAM.REL_OPS, TEAM.TASKCLUSTER],
  [TASK.BUILD_PEER]: [TEAM.BUILD],
  [TASK.SYMBOL]: [TEAM.BUILD],
  [TASK.IMAGE]: [TEAM.TESTS],
  [TASK.UNIT]: [TEAM.TESTS, TEAM.ENG_PROD],
  [TASK.MOCHITEST]: [TEAM.TESTS, TEAM.ENG_PROD],
  [TASK.REF]: [TEAM.TESTS, TEAM.ENG_PROD],
  [TASK.WEB_PLATFORM]: [TEAM.TESTS, TEAM.ENG_PROD],
  [TASK.E10S]: [TEAM.TESTS, TEAM.ENG_PROD],
  [TASK.TALOS]: [TEAM.TESTS],
  [TASK.TIER2]: [TEAM.TASKCLUSTER],
  [TASK.TIER1]: [TEAM.TASKCLUSTER],
  [TASK.SIGNED]: [TEAM.REL_ENG],
  [TASK.MAR]: [TEAM.REL_ENG],
  [TASK.L10N]: [TEAM.REL_ENG]
};

var PHASES = {
  'TaskCluster': [TASK.WORKER, TASK.AMI, TASK.MACH, TASK.MOZHARNESS],
  'Release Operations': [TASK.TRY, TASK.BUILD_PEER],
  'Symbols': [TASK.SYMBOL],
  'Tests': [TASK.IMAGE, TASK.UNIT, TASK.MOCHITEST, TASK.REF, TASK.WEB_PLATFORM, TASK.E10S],
  'Talos': [TASK.TALOS],
  'Tier 2': [TASK.TIER2],
  'Tier 1': [TASK.TIER1],
  'Release Engineering': [TASK.SIGNED, TASK.MAR, TASK.L10N]
};

var MATRIX = {
  'Linux x64 debug': {
    blocked: 'AWS Sucks',
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: true,
    [TASK.MOZHARNESS]: true,
    [TASK.TRY]: true,
    [TASK.BUILD_PEER]: true,
    [TASK.SYMBOL]: true,
    [TASK.IMAGE]: true,
    [TASK.UNIT]: true,
    [TASK.MOCHITEST]: true,
    [TASK.REF]: true,
    [TASK.WEB_PLATFORM]: true,
    [TASK.E10S]: true,
    [TASK.TALOS]: null,
    [TASK.TIER2]: true,
    [TASK.TIER1]: true,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x64 opt': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: true,
    [TASK.MOZHARNESS]: true,
    [TASK.TRY]: true,
    [TASK.BUILD_PEER]: true,
    [TASK.SYMBOL]: true,
    [TASK.IMAGE]: true,
    [TASK.UNIT]: true,
    [TASK.MOCHITEST]: true,
    [TASK.REF]: true,
    [TASK.WEB_PLATFORM]: true,
    [TASK.E10S]: true,
    [TASK.TALOS]: false,
    [TASK.TIER2]: true,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x64 PGO': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: true,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: true,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x64 ASAN': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: true,
    [TASK.MOZHARNESS]: true,
    [TASK.TRY]: true,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: true,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x64 Hazard': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x64 ???': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x32 debug': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x32 opt': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Linux x32 PGO': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Android 4.0 API15+ debug': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Android 4.0 API15+ opt': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Android 4.2 x86 opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Android 4.3 API15+ debug': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Android 4.3 API15+ opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 2012 x64 debug': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: true,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 2012 x64 opt': {
    blocked: 'bug 111111',
    [TASK.WORKER]: true,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 2012 x64 PGO': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 7 opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 7 debug': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 8 opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 8 debug': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 10 opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'Windows 10 debug': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'OS X debug': {
    blocked: null,
    [TASK.WORKER]: true,
    [TASK.AMI]: true,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'OS X opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'OS X cross-compiled debug': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  },
  'OS X cross-compiled opt': {
    blocked: null,
    [TASK.WORKER]: false,
    [TASK.AMI]: false,
    [TASK.MACH]: false,
    [TASK.MOZHARNESS]: false,
    [TASK.TRY]: false,
    [TASK.BUILD_PEER]: false,
    [TASK.SYMBOL]: false,
    [TASK.IMAGE]: false,
    [TASK.UNIT]: false,
    [TASK.MOCHITEST]: false,
    [TASK.REF]: false,
    [TASK.WEB_PLATFORM]: false,
    [TASK.E10S]: false,
    [TASK.TALOS]: false,
    [TASK.TIER2]: false,
    [TASK.TIER1]: false,
    [TASK.SIGNED]: false,
    [TASK.MAR]: false,
    [TASK.L10N]: false
  }
};

Object.assign(window, { TEAM, LABELS, TASK, OWNERS, PHASES, MATRIX });
